config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :posts, path: 'blog'
  
  post '/contact', to: 'welcome#contact'
	root 'welcome#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :posts

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :name, :position, :avatar, presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/system/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/system/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/system/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/system/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, :image, :author, presence: true
	belongs_to :author

	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	def self.search(search)
  	where("title ILIKE ?", "%#{search}%") 
	end

	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
def index
  @posts = Post.all
  if params[:search]
    @posts = Post.search(params[:search]).order("created_at DESC").page(params[:page]).per(6)
  else
    @posts = Post.all.order('created_at DESC').page(params[:page]).per(6)
  end
end

	def show
		@post = Post.friendly.find(params[:id])
		@posts = Post.order("created_at desc").limit(4).offset(1)
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :contact
  layout false

  def index
    @style = Rails.env.development? ? Rails.application.assets['welcome'].to_s : File.read(Rails.root.join('public/assets/' + Rails.application.assets_manifest.assets["welcome.css"]))
  end

  def contact
    Request.notify(params[:contact]).deliver_now
    response.set_header("AMP-Access-Control-Allow-Source-Origin", request.protocol + request.host_with_port)
    render json: {}, status: 200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> IT Consultancy - Software Development Services - Naprok Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>

        <!-- Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104063296-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-104063296-1');
</script>
<!-- Microdata -->
<script type="application/ld+json">{
"@context": "http://schema.org",
"@type": "Blog",
"name": "Naprok blog",
"url": "http://naprok.com/blog",
"description": "Naprok is an IT consultancy offering the full-stack developers from outsourcing vendors to your in-house staff. Our team screens the engineers in advance to provide you with the remote staff who meet all expectation you're looking for",
"sameAs": [
"https://www.facebook.com/NaprokOutstaffing/",
"https://plus.google.com/b/113955821309509306078/?hl=ru",
"https://www.linkedin.com/company/17920121/",
"https://twitter.com/NaprokOutstaff"
],

"publisher": {
"@type": "Organization",
"name": "Naprok Outstaffing",
"logo": {
"@type": "imageObject",
"url": "http://naprok.com/assets/logo-f3bae7421dd76b34ed708022347e9dbaa75130fa2d41387e2cbb8988df5575b0.svg"
}
}
}
]
}</script>
    <%= yield :head %>
</head>
  <body>
    <!--
    <%= render 'shared/alerts' %> -->
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_comments.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
s.src = '//naprok-blog.disqus.com/embed.js';
this.page.url = '<%= url_for(@post) %>';
this.page.identifier = '<%= @post.id %>';
this.page.title = '<%= @post.title %>';
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://naprok-blog.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>

                            

app/views/posts/index.html.erb
<div id="posts">
    <div class="container">
        <div class="row">
              <% if @posts.present? %>
                <% @posts.each do |post| %>
                <div class="col-md-4">
                  <div class="posts-item">
                    <div class="post-preview" style='background: url("<%= post.image.url %>") no-repeat; background-size: cover; background-position: center;'></div>
                        <%= image_tag post.author.avatar.url(:thumb), class: 'avatar'%>
                    <p class="about-post">
                      <i>
                        Created <%= post.created_at.strftime("%B %d, %Y") %> <br /> 
                        by <%= post.author.name %>
                      </i>
                    </p>
                    <div class="description">
                      <h2><%= post.title %></h2>
                      <%= link_to post_path(post) do %>
                        <button class="read-more">Read more</button>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
            <p>There are no posts <%= params[:search] %>.</p>
          <% end %>
          <div class="clearfix"></div>
          <div class="text-center"><%= paginate @posts %></div>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<% content_for :head do %>
  <%= tag :meta, property:"og:type", content:'website' %>
  <%= tag :meta, property:"og:title", content: @post.title %>
  <%= tag :meta, property:"og:image", content: request.protocol + request.host_with_port + image_path( @post.image.url) %>
  <%= tag :meta, property: "twitter:card", content: "summary" %>
  <%= tag :meta, property: "twitter:title", content: @post.title %>
  <%= tag :meta, property:"twitter:image", content: request.protocol + request.host_with_port + image_path( @post.image.url) %>
  <script>
    document.querySelector('script[type="application/ld+json"]').remove();
  </script>
  <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "Article",
      "name" : "<%= @post.title %>"
      "author" : {
        "@type" : "Person",
        "name" : "<%= @post.author.name %>"
      },
      "datePublished" : "<%= @post.created_at.strftime("%Y-%m-%d") %>",
      "image" : "https://naprok.com/blog/<%= @post.image.url %>",
      "articleSection" : "Project Management",
      "articleBody" : "<%= @post.body.html_safe %>",
      "url" : "https://naprok.com/blog/<%= url_for(@post) %>"
    }
  </script>
<% end %>
<div class="post-photo" style='background: url("<%= @post.image.url %>");background-repeat:repeat-x;background-position: top center;background-attachment: fixed;background-size: cover;'>
</div>
<div class="container post-container">
    <div class="col-md-12">
      <h1><%= @post.title %></h1>
      <p>
        <i class="fa fa-user" aria-hidden="true"></i>
        <i><%= @post.author.name %></i>
        <i class="fa fa-clock-o" aria-hidden="true"></i>
        <i><%= @post.created_at.strftime("%B %d, %Y") %></i>
      </p>
      <p class="post-text"><%= @post.body.html_safe %></p>
    </div>
    <div class="comments">
      <%= render 'comments' %>
    </div>
</div>

app/views/request/notify.html.erb
<p><%= @message %></p>



| Naprok </br>
| <%= DateTime.now.strftime("%c") %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="col-31 info">
    <img src=<%= asset_url("logo-header.png") %> alt="Naprok logo" height="40" width="179" class="logo"></img>
    <div class="cpr">
      Copyright © 2018 Naprok. Privacy Policy
    </div>
  </div>
  <div class="col-22 bottom-navs">
    <a href="/">HOME</a>
    <a href="https://naprok.com/#2">ABOUT US</a>
    <a href="https://naprok.com/#3">ADVANTAGES</a>
    <a href="https://naprok.com/#4">SCREENING</a>
    <a href="https://naprok.com/#5">CONTACT US</a>
  </div>
  <div class="col-28 contacts">
    <p>200, Shevchekno Street, <br/>
      Cherkasy, Ukraine, 18000 <br/>
    <p>+38 (097) 753 57 31<br/>
      contact@naprok.com</p>
  </div>
  <div class="col-19 media">
    <div>
      <a href='https://www.facebook.com/NaprokOutstaffing/' target='_blank' rel="noopener">
        <span class="fa-stack">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fab fa-facebook-f fa-inverse fa-stack-1x"></i>
        </span>
      </a>
      <a href='https://www.linkedin.com/company/17920121/' target='_blank' rel="noopener">
        <span class="fa-stack">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fab fa-linkedin-in fa-inverse fa-stack-1x"></i>
        </span>
      </a>
      <a href='#' target='_blank' rel="noopener">
        <span class="fa-stack">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fab fa-instagram fa-inverse fa-stack-1x"></i>
        </span>
      </a>
      <a href='https://twitter.com/NaprokOutstaff' target='_blank' rel="noopener">
        <span class="fa-stack">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fab fa-twitter fa-inverse fa-stack-1x"></i>
        </span>
      </a>
      <a href='<%= posts_url %>' target='_blank' rel="noopener">
        <span class="fa-stack">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fab fa-blogger-b fa-inverse fa-stack-1x"></i>
        </span>
      </a>
    </div>
    <button class="talk-button">SUBSCRIBE</button>
  </div>
</div>

app/views/shared/_head.html.erb
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

    <%= yield :head %>

app/views/shared/_header.html.erb
  <div class="nav">
    <div class="container">
      <div class="col-md-3">
        <div class="logo">
          <a href="">
            <%= image_tag "logo.svg", class: "img-responsive" %>
          </a>
        </div>
      </div>
      <div class="col-md-5">
          <ul class="list-inline">
            <li class="menu-item"><%= link_to "Home", root_path %></li>
            <li class="menu-item"><%= link_to "About us", "https://naprok.com/#2" %></li>
            <li class="menu-item"><%= link_to "Contact us", "https://naprok.com/#5" %></li>
          </ul>
      </div>
      <div class="col-md-4">
        <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
          <%= button_tag(type: "submit") do %>
            <i class="fas fa-search" aria-hidden="true"></i>
          <% end %>
        <% end %>
			</div>
     </div>
  </div>

app/views/welcome/_1-search-for-dedicated-leading-team.html.erb
<div class="section-1" id='1'>
  <div class="container ">
    <div class="content col-35 container-padding">
      <div class="big-text col-9">
        SEEKING FOR DEDICATED LEADING TEAMS?
      </div>
      <div class="small-text col-8">
        We believe the original technical specialists and team players take place from software companies they work at. Do you?
      </div>
      <div class="col-10 section1-butt">
        <a href="#5">
          <button class="talk-button">LET'S TALK</button>
        </a>
      </div>
    </div>
    <div class="col-5 bg padding-bg">
      <div class="bg-section"></div>
    </div>
  </div>
</div>

app/views/welcome/_2-why-we.html.erb
<div class="section-2" id='2'>
  <div class="container">
    <div class="content">
      <div class="flex-container-menu">
        <div class="stripe stripe-1 tab" data-tab='who'>WHO WE ARE</div>
        <div class="stripe stripe-2 tab" data-tab='why'>WHY NAPROK</div>
        <div class="stripe stripe-3 tab" data-tab='how'>HOW CAN WE HELP YOU</div>
      </div>

      <div class='flex-container-tabs'>
        <div class='col-5'>
          <div class='tab-content text' data-tab='who'>
            <div class="title">
              WHO WE ARE
            </div>
            <div class="small-text">
              Naprok is an independent IT consulting company which provides screened engineers from service-based companies to your product one. Our team is good at finding out professional staff members, or, indeed, a small team who you achieving long-term plans with.
            </div>
          </div>

          <div hidden class="tab-content text" data-tab='why'>
            <div class="title">
              WHY NAPROK
            </div>
            <div class="small-text">
              Hiring dedicated developers requires your awareness about particularities of outstaffing inside out. We can handle this and match candidates with relevant expertise to extend either your in-house staff or current remote team.
            </div>
          </div>

          <div hidden class="tab-content text" data-tab='how'>
            <div class="title">
              HOW CAN WE HELP YOU
            </div>
            <div class="small-text">
              Your time has appreciated value, and we’re conscious of your tight schedule and time frame. Likewise we understand that the best option to run dedicated team more rapidly is to hire experienced in your area developers with appropriate tech stack. Thus, we manage to take over every technical and procedural aspects so that you have to make a small effort to set up dedicated employees.
            </div>
          </div>
        </div>

        <div class='col-1'></div>

        <div class='col-4'>
          <div class='who-we-are background tab-content' data-tab='who'></div>
          <div hidden class="col-5 why-naprok background tab-content" data-tab='why'></div>
          <div hidden class="col-5 help background tab-content" data-tab='how'></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_3-how-we-work.html.erb
<div class="section-3" id='3'>
  <div class="content-right">
    <div class="col-10 head">THE WAY WE SERVE YOU</div>
    <div class="col-10">
      <div class="col-2 block ">
        <div class="head red">GATHERING OF GEEKS</div>
        <div class="body">We had gotten ahold of software vendors whose developers are able to work using team extension model</div>
      </div>
      <div class="col-16 block block-media"></div>
      <div class="col-2 block">
        <div class="head green">IN THE LIMELIGHT</div>
        <div class="body">All in all, we have the database with verified engineers, who’re willing to get started in case their availability</div>
      </div>
      <div class="col-12 block block-media"></div>
      <div class="col-2 block">
        <div class="head blue">APPROPRIATE MATCHES</div>
        <div class="body">We browse through all proven CVs to find the best matches toward concerning your requirements</div>
      </div>
    </div>
    <!-- 2-r -->
    <div class="col-10 block-margin">
      <div class="col-15 block-footer"></div>
      <div class="col-25 block">
        <div class="head yellow">UNDER THE MICROSCOPE</div>
        <div class="body">Our specialists have screened each of candidate to be confident that all developers conforms to their quality level</div>
      </div>
      <div class="col-15 block-media"></div>
      <div class="col-19 block">
        <div class="head green-2">KNOCK-KNOCK</div>
        <div class="body">Your business is growing, hence further extension of staff is inevitable. Depict us perfect candidates you need. We hang upon your specifications</div>
      </div>
    </div>
  </div>
  <!-- BG!!!!! -->
  <div>
    <div class="bg hiden-sm"></div>
  </div>
  <!-- BG!!!!! -->
  <div class="content-right">
    <div class="col-10 block-margin">
      <div class="col-17 block-footer"></div>
      <div class="col-2 block">
          <div class="head yellow-2">WE'RE ALMOST THERE</div>
          <div class="body">The final interview between you and developers to confirm cooperation with employees you choose</div>
      </div>
      <div class="col-17 block-media"></div>
      <div class="col-17 block">
          <div class="head green-3">BEST CANDIDATES</div>
          <div class="body">Narrow down the number of candidates, we provide you the best crops amongst all developers</div>
      </div>
    </div>
    <!-- 2-r -->
    <div class="col-10 block-margin">
      <div class="col-25 block ">
        <div class="head red-2">LET'S THE TEAM ROCK UP</div>
        <div class="body">Contract between your company and the company which designate programmers work for</div>
      </div>
      <div class="col-1 block-media"></div>
      <div class="col-2 block">
        <div class="head green-4">KEEP OPTIONS OPEN</div>
        <div class="body">You have the final word here. Hence, you’ll look through approved CVs yourself and decide who you'd be more predisposed to hire</div>
      </div>
      <div class="col-16 block-media"></div>
      <div class="col-17 block">
        <div class="head blue-1">ARE THEY READY?</div>
        <div class="body">We request vendors whether certain engineers will be available and ready to get started for the project</div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_4-screening-work.html.erb
<div class="section-4" id='4'>
  <div class="content-right">

    <div class="col-10 title">
      HOW THE SCREENING WORKS
    </div>

    <div class="col-45 bg"></div>

    <div class="col-45 section4-text">
      <div class="text" >
        <div class="col-4 media-mobile">
          <div class="head">IN ENGLISH, PLEASE</div>
          <div class="body">Considering your dedicated developers have to communicate directly with you and other
            members, we determine whether they’re fluent in English. Apart from speaking, the high-level helps
            programmers to speed up their workflow and solve any issues that might appear
          </div>
        </div>
        <div class="col-4 media-mobile">
          <div class="head">DEDICATION AND COMMITMENT</div>
          <div class="body">Beyond perfect English and technical competence, we screen over engineer’s politeness,
            adequacy and identity. This step is vital to be convinced about leadership skills and ability to work
            integrity with the team
          </div>
        </div>
      </div>

      <div class="text">
        <div class="col-4 media-mobile">
          <div class="head">TECH STACK</div>
          <div class="body">Given that all candidates aren’t identical and have different proficiency, we check each of
            them by experts in particular skills. Due to outstaffing services, each of employee is regarded as an
            autonomous developer, who has strong points and suited to carry out certain tasks much better than others.
            We are mindful of these peculiarities as well
          </div>
        </div>
        <div class="col-4 media-mobile">
          <div class="head">THE TEST TRIALS</div>
          <div class="body">For afters, we’ve got test project to estimate practical experience in accordance with
            theoretical knowledge. It's a great chance for candidates to show their critical thinking,professional
            competence and creative abilities. We believe that lead engineers deliver upon expectations with the real
            challenges only
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_5-contact-us.html.erb
<div class="section-5" id='5'>
  <div class="col-5 left hiden-sm"></div>
  <div class="col-5 bg-form">
    <div class="col-4 contact-form">
      <div class="head">LET'S START</div>
      <div class="body">Write your message to contact us and discuss the details of the cooperation</div>
      <%= form_tag( "/contact", method: "post", id: 'my-form', onsubmit: 'return false', target: "_top" )  do %>
        <input type="email" class='text-input' name="email" placeholder="email" [value]="contactEmail" required><br>
        <input type="text" class='text-input' name="message" placeholder="message" [value]="contactMessage" required><br>
        <input type="submit" class='submit-input' onclick="sendMessage()" value="SEND MESSAGE">
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="col-31 info">
      <img  src=<%= asset_url("logo.png")%> alt="Naprok logo" height="40" width="179" class="logo"></img>
      <div class="cpr">
        Copyright © 2018 Naprok. Privacy Policy
      </div>
    </div>
    <div class="col-22 bottom-navs">
      <a href="#1">HOME</a><br/>
      <a href="#2">ABOUT US</a><br/>
      <a href="#3">ADVANTAGES</a><br/>
      <a href="#4">SCREENING</a><br/>
      <a href="#5">CONTACT US</a><br/>
    </div>
    <div class="col-28 contacts">
      <p>200, Shevchekno Street, <br/>
        Cherkasy, Ukraine, 18000 <br/>
      <p>+38 (097) 753 57 31 <br/>
        <a href="mailto:contact@naprok.com" target="_top" class='footer-link'>
          contact@naprok.com
        </a>
      </p>
    </div>
    <div class="col-19 media">
      <div>
        <a href='https://www.facebook.com/NaprokOutstaffing/' target='_blank' rel="noopener">
          <span class="fa-stack">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fab fa-facebook-f fa-inverse fa-stack-1x"></i>
          </span>
        </a>
        <a href='https://www.linkedin.com/company/17920121/' target='_blank' rel="noopener">
          <span class="fa-stack">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fab fa-linkedin-in fa-inverse fa-stack-1x"></i>
          </span>
        </a>f
        <a href='#' target='_blank' rel="noopener">
          <span class="fa-stack">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fab fa-instagram fa-inverse fa-stack-1x"></i>
          </span>
        </a>
        <a href='https://twitter.com/NaprokOutstaff' target='_blank' rel="noopener">
          <span class="fa-stack">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fab fa-twitter fa-inverse fa-stack-1x"></i>
          </span>
        </a>
        <a href='<%= posts_url %>' target='_blank' rel="noopener">
          <span class="fa-stack">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fab fa-blogger-b fa-inverse fa-stack-1x"></i>
          </span>
        </a>
      </div>
      <button class="talk-button">SUBSCRIBE</button>
      <div class="cpr media-block">
        Copyright © 2018 Naprok. Privacy Policy
      </div>
    </div>
  </div>
</footer>

app/views/welcome/_header.html.erb
<div class="header">
  <div class="col-5 logo-header " >
    <img class="logo-size" src=<%= asset_url("logo-header.png")%> alt="Naprok logo" ></img>
  </div>
  <div class="col-5 menu-header">
    <div class="nav-panel">
      <a href="#1">HOME</a>
      <a href="#2">ABOUT US</a>
      <a href="#3">ADVANTAGES</a>
      <a href="#4">SCREENING</a>
      <a href="#5">CONTACT US</a>
    </div>
    <div class="butt-mobile">
      <input type="checkbox" id="m1" class="hidden-menu-ticker">
      <label class="btn-menu" for="m1">
        <span class="first"></span>
        <span class="second"></span>
        <span class="third"></span>
      </label>
      <ul class="hidden-menu">
        <li><a href="#1" onclick="hideBurgerMenu()">HOME </a></li>
        <li><a href="#2" onclick="hideBurgerMenu()">ABOUT US</a></li>
        <li><a href="#3" onclick="hideBurgerMenu()">ADVANTAGES</a></li>
        <li><a href="#4" onclick="hideBurgerMenu()">SCREENING</a></li>
        <li><a href="#5" onclick="hideBurgerMenu()">CONTACT US</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/welcome/_left-nav.html.erb
<div class="left-nav hiden-sm" id='left-nav'>
  <a [href]="'#' + (navState.current - 1).toString()" class="top-button">
    <img src=<%= asset_url("nav-top.png")%>
      width="20"
      height="20"
      tabindex="0"
      role="button">
    </img>
  </a>

  <a [class]="navState.current == '1' ? 'active' : ''" href="#1">01</a>
  <a [class]="navState.current == '2' ? 'active' : ''" href="#2">02</a>
  <a [class]="navState.current == '3' ? 'active' : ''" href="#3">03</a>
  <a [class]="navState.current == '4' ? 'active' : ''" href="#4">04</a>
  <a [class]="navState.current == '5' ? 'active' : ''" href="#5">05</a>

  <a [href]="'#' + (navState.current + 1).toString()" class="bot-button">
    <img src=<%= asset_url("nav-bot.png")%>
    width="20"
    height="20"
    tabindex="0"
    role="button">
    </img>
  </a>
</div>